### ISSUE TITLE
Command inconsistency

### ISSUE THREAD

**Issue by ghost** [ANT1pattern/webpage#1]
- command 'help' states the command 'services', but actual command is 'service' without the **S**
- command 'references' leads to an error 'Exception: ReferenceError: refInfo is not defined'
- command 'service consult' empty
- command 'service develop', maybe development is a better term; it is 'every**thing** you need and want'
- command 'service scale' leads to 'undefined'
- command 'service devops' empty

Everything else works pretty good. Good work tosh1!

**Comment by froid1911** [comment]
@robertberlin, please review.
Maybe you can help me with some scale and devops descriptions?

**Comment by ghost** [comment]
You improved it on a branch, right? Is there an online instance, so I can retest it?

**Comment by froid1911** [comment]
https://ipfs.io/ipfs/QmaPpZwUP1jztTmA8HAjKVVwaQBe4LLEowHcP1snUS1vRy/
